name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  integration:
    name: Integration
    uses: ./.github/workflows/integration.yml

  publish:
    name: Publish
    needs:
      - integration
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 18

      - name: Install dependencies
        run: pnpm install

      - name: Generate changelog
        uses: hideoo/changelogithub-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
